version: "3.9"
services:
  db:
    container_name: postgresql
    image: postgres
    env_file:
      - .env
    volumes:
      - ./.docker/volumes/db:/var/lib/postgresql/data

  api:
    container_name: rails
    build:
      context: .
      dockerfile: .docker/gp-api/Dockerfile
    env_file:
      - .env
    volumes:
      - ./gp-api:/gp-api
    ports:
      - "3000:3000"
    depends_on:
     - db
