default: &default
  adapter: postgresql
  encoding: unicode
  host: db
  username: <%= ENV.fetch("POSTGRES_USER") %>
  password: <%= ENV.fetch("POSTGRES_PASSWORD") %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: gp_development

test:
  <<: *default
  database: gp_test
